# ================= CPU =================
CPU_ACTIVE_THRESHOLD=60 # CPU Load alert
CPU_TEMP_THRESHOLD=65   # CPU Temp Alert

# ================= HOST =================
HOST_NAME="🖥️ HP Linux Server"

# ================= GPU =================
GPU_TEMP_THRESHOLD=65

# ================= DISK =================
# (Boot SSD)
BOOT_SSD_REALLOC=0
BOOT_SSD_WEAR=94

# (Immich SSD)
IMMICH_SSD_REALLOC=1
IMMICH_SSD_WEAR=100

# (Camera HDD)
CAMERA_HDD_REALLOC=0
CAMERA_HDD_PENDING=0
CAMERA_HDD_OFFLINE=0
CAMERA_HDD_REPORTED=1

# (Data HDD)
DATA_HDD_REALLOC=0
DATA_HDD_PENDING=0
DATA_HDD_OFFLINE=0
DATA_HDD_REPORTED=4

DISK_TEMP_WARN=43

HDD_CHECK_INTERVAL=60     # minutes [For temperature only]
SSD_CHECK_INTERVAL=60     # minutes [For temperature only]

# ===== DUST / COOLING DETECTION =====
# CPU considered "idle / light load" below this
DUST_CPU_ACTIVE_MAX=35     # %

# Temperature considered too high for low CPU
DUST_CPU_TEMP_MIN=60        # °C

# Condition must persist for this long (in minutes)
DUST_DETECT_DURATION=5

# Mean Absolute Deviation (MAD)
DUST_CPU_TEMP_MAD_MAX=3
