#######################################
# Camera Identification
#######################################

MAIN_CAMERA_MAC="58:c5:87:a7:07:e1"
MINI_CAMERA_MAC="38:54:f5:2c:f5:77"

SUBNET="192.168.3.0/24"

#######################################
# RTSP Settings (per camera)
#######################################

RTSP_PORT=554

CAMERA_RTSP_PATH="/live/ch00_0"

#######################################
# Per-Camera Video Format
#######################################

MAIN_CAMERA_FILE_EXTENSION="mp4"
MINI_CAMERA_FILE_EXTENSION="mkv"

#######################################
# Recording Settings
#######################################

SEGMENT_DURATION=300        # 5 minutes

#######################################
# Storage
#######################################

OUTPUT_DIR="/home/hpserver/Ramdisk/Camera_Recording"
ARCHIVE_DIR="/mnt/data/Camera-Recordings-Archive"

#######################################
# Upload Interval
#######################################

POLL_INTERVAL=150
